diad/config/routes.rb
Rails.application.routes.draw do

  root 'diad#index'
  get 'diad/news' => 'diad#news'
  get 'diad/tour' => 'diad#tour'
  get 'diad/music' => 'diad#music'
  get 'diad/musicsimple' => 'diad#musicsimple'
  get 'diad/videos' => 'diad#videos'
  get 'diad/store/rmfromcart' => 'diad#rmfromcart'
  get 'diad/store/viewcart' => 'diad#viewcart'
  get 'diad/store/addtocart' => 'diad#itemtocart'
  get 'diad/store/tender' => 'diad#tender'
  get 'diad/store/thankyou' => 'diad#thankyou'
  post "/diad/store/checkout" => "charges#charge_card"
  get 'diad/products' => 'diad#items'
  get 'diad/photos' => 'diad#photos'
  get 'diad/download' => 'diad#download'
  get 'diad/about' => 'diad#about'
  get "/log-in" => "sessions#new"
  post "/log-in" => "sessions#create"
  get "/log-out" => "sessions#destroy", as: :log_out
  resources :users
  post "users/new" => "users#create"

end

diad/app/controllers/diad_controller.rb
require 'useragent'

class DiadController < ApplicationController
  before_action :checklogin, only: [ :viewcart, :itemtocart ]
  force_ssl only: [ :viewcart, :itemtocart, :tender, :rmfromcart ]


  def index
    @shows = Show.all
  end

  def news
  end

  def photos
    @image_urls = Array.new
    @image_urls = [ "mainpoolshotWEB.jpg" ]
  end

  def about
  end

  def download
  end

  def tour
  end

  def music
	user_agent = UserAgent.parse(request.user_agent)
  unless user_agent.browser == "Chrome"
    redirect_to diad_musicsimple_path
  end
  end

  def musicsimple
  end

  def viewcart
    @items = current_user.cart.items
    itemsincart = @items.count
    puts "items in cart is here:"
    puts itemsincart
    unless itemsincart.to_i > 0
      flash[:notice] = "No items in cart."
      redirect_to diad_products_path
    end
    cartid = current_user.cart.id
    @total, @subtotal, @tax, @shipping = Item.rmitem(cartid)
    puts "subtotal is here:"
    puts @subtotal
    puts "Tax is here:"
    puts @tax
    puts "shipping is here:"
    puts @shipping
    if @tax.to_i > 99
      @tax = @tax.to_i.to_s.scan(/./)
      @tax = @tax[0..-3].join + '.' + @tax[-2..-1].join
    else
       @tax = @tax.to_i.to_s
       @tax = '0' + '.' + @tax
    end
    @tax = '$' + @tax
      if @subtotal.to_i > 99
        @subtotal = @subtotal.to_i.to_s.scan(/./)
        @subtotal = @subtotal[0..-3].join + '.' + @subtotal[-2..-1].join
      end
        @subtotal = '$' + @subtotal.to_s
    if current_user.cart.total.to_i > 99
      @total = current_user.cart.total.to_i.to_s.scan(/./)
      @total = @total[0..-3].join + '.' + @total[-2..-1].join
    end
    @total = '$' + @total.to_s
    if @shipping.to_i > 99
      @shipping = @shipping.to_i.to_s.scan(/./)
      @shipping = @shipping[0..-3].join + '.' + @shipping[-2..-1].join
      @shipping = '$' + @shipping.to_s
    end
  end

  def emptycart
    current_user.cart.items.delete_all
    current_user.cart.total = 0
    current_user.cart.save
  end

  def itemtocart
      params[:cartid] = current_user.cart.id
      quantity = params[:quantity]
      params[:size] ||= nil
      if quantity[0] == ""
        quantity[0] = 1
      end
      @total = Item.additem(params[:itemid], quantity[0], params[:cartid], params[:size])
      redirect_to diad_products_path, notice: "Successfully Added to Cart"
  end

  def items
    @items = Item.all
    unless current_user.nil?
       unless Cart.find_by_user_id(current_user.id).nil?
        if current_user.cart.total.to_i > 99
         @total = current_user.cart.total.to_i.to_s.scan(/./)
         @total = @total[0..-3].join + '.' + @total[-2..-1].join
          end
       else
         cartparams = Hash.new
         cartparams[:user_id] = current_user.id
         cartparams[:total] = 0
         Cart.create(cartparams)
         @total = current_user.cart.total.to_i
       end
    else
      @total = 0
    end
  end

  def rmfromcart
       puts "I'm inside of rmfromcart now"
       cartid = current_user.cart.id
      item = Item.find_by_id(params[:id]).delete
       @total, @subtotal, @tax, @shipping = Item.rmitem(cartid)
       if @total.to_i > 0
      redirect_to diad_store_viewcart_path
       else
         flash[:notice] = "Cart is empty, pick your poison."
         redirect_to diad_products_path
         end
  end

  def tender
    if current_user.cart.total.to_i > 99
#    @total = current_user.cart.total.to_i
      cartid = current_user.cart.id
      @total, @subtotal, @tax, @shipping = Item.rmitem(cartid)
      puts "debug---"
      puts @total
      puts @subtotal
      puts @tax.to_i
      puts @shipping
      puts "debug----"
     @total = (@total.to_i + @tax.to_i + @shipping.to_i)
    @total = @total.to_s.scan(/./)
    @displaytotal = '$' + @total[0..-3].join + '.' + @total[-2..-1].join
    else
      flash[:notice] = 'No items in cart.'
      redirect_to diad_products_path
      end
  end

  def videos
  end

  def thankyou
  end

  def checklogin
    unless current_user 
      redirect_to log_in_path
    end
  end


end

diad/app/helpers/diad_helper.rb
module DiadHelper
end

diad/app/views/diad/about.html.erb
<html>
<head>

</head>
<h1>Coming Soon.</h1>
</html>

diad/app/views/diad/download.html.erb
<html>
<head>

</head>
<h1>Coming Soon.</h1>
</html>

diad/app/views/diad/index.html.erb
<html>
<head>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.6.1/css/font-awesome.min.css">
  <title>DeathisaDialogue | Official Site</title>
  <%= stylesheet_link_tag    'application', 'diadmain', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <%= favicon_link_tag 'favicon.png' %>

  <nav class="navbar navbar-default navbar-fixed-top headblack" role="navigation">
    <div class="navbar-header">
      <a class="navbar-brand" href="http://www.deathisadialogue.com">
        <%= image_tag("Logoandname.png") %>
      </a>
    </div>
    <%= form_tag('http://www.fanbridge.com/signup/1.5/submit?userid=67920', id: 'fanbridgesignup', authenticity_token: false, method: :post, remote: true, class: "nav-inline form-inline") do %>
        <%= text_field_tag 'firstname', nil, placeholder: 'First Name', size: 8, class: 'form-controle-xsm form-email' %>
        <%= text_field_tag 'lastname', nil, placeholder: 'Last Name', size: 8, class: 'form-controle-xsm form-email' %>
        <%= text_field_tag 'email', nil, placeholder: 'Email', size: 20, class: 'form-control-xsm form-email' %>
        <%= text_field_tag 'zip', nil, placeholder: 'Zipcode', size: 6, class: 'form-control-xsm form-email' %>
        <%= submit_tag "Get Updates!", onclick: "alertify.success('Got it! We will be in touch.', function() {},'popup1');", class: 'btn btn-default btn-sm btn-email' %>
    <% end %>
    <script>
      $("#fanbridgesignup").bind("ajax:send", function(e){
        $("#firstname").val('');
        $("#lastname").val('');
        $("#email").val('');
        $("#zip").val('');
      });
    </script>
    <div id="genlinks">
      <div class="container">
        <ul class="nav nav-bar navbar-nav">
          <li ><%= link_to "News", root_path %>
            <%= link_to "Tour", :anchor => 'tour' %>
            <%= link_to "Music", diad_music_path %>
            <%= link_to "Videos", :anchor => 'video' %>
            <%= link_to "Photos", diad_photos_path %>
            <%= link_to "Store", diad_products_path %>
            <%= link_to '', "https://www.facebook.com/deathisadialogue", :class => "fa fa-facebook navbar-right", :target => '_blank' %>
            <%= link_to '', "https://www.twitter.com/deathisadialog", :class=> "fa fa-twitter navbar-right", :target => '_blank' %>
            <%= link_to '', "https://play.spotify.com/album/5LfJ9J6lwySoakYxnlqXOH", :class=> "fa fa-spotify navbar-right", :target => '_blank' %>
            <%= link_to '', "https://www.instagram.com/jasonleediad", :class=> "fa fa-instagram navbar-right", :target => '_blank' %>
            <%= link_to '', "https://www.youtube.com/user/Deathisadialogue/videos", :class=> "fa fa-youtube navbar-right", :target => '_blank' %>
          </li>
        </ul>
      </div>
    </div>
  </nav>
</head>
<body class="blackwall">
<div class="jumbotron jumbotron-sized jumboalign">
  <div class="bg">
  </div>
    <div id="tour"></div>
  </div>
</div>
<div class="jumbotron jumbotron-sized jumboalign">
  <div class="bg">
  </div>
  <div class="container">
    <h2>Tour Dates</h2>
    <div class="table-responsive">
      <table class="table">
        <tbody>
        <tr>
          <td>Date</td>
          <td>Venue</td>
          <td>City</td>
          <td>Age</td>
          <td>Directions</td>
          <td>Tickets</td>
        </tr>
        <% @shows.each do |show| %>
            <tr>
            <td><%= show.date %></td>
              <td><%= show.venue %></td>
              <td><%= show.city %></td>
              <td><%= show.age %></td>
              <td><%= link_to 'Directions', show.directions, :target => "_blank" %></td>
              <td><%= button_to 'Buy', show.tickets, method: :get, :class => 'btn-xs btn-sharp', form: {target: '_blank'} %></td>
            </tr>
              <% end %>
        </tbody>
      </table>
    </div>
  </div>

 <div class="content container">
    <%= image_tag("albummockup2.png", :class => 'albumautoscale') %>
 </div>

  <div id="video"></div>
  <div class="content">
  </div>
</div>
<div class="jumbotron jumbotron-sized jumboalign">
  <div class="bg">
  </div>
  <div>Listen to tracks off Call of The Siren!</div>
  <div class="content">
  <iframe width="854" height="480" src="https://www.youtube.com/embed/f5g3YRU3X0k" frameborder="0" allowfullscreen></iframe>
  </div>
 </div>
 <div class="jumtotron jumbotron-sized jumboalign" >
  <div class="content">
   <iframe width="854" height="480" src="https://www.youtube.com/embed/HYiSgT6jQn0" frameborder="0" allowfullscreen></iframe>
  </div>
</div>

<div class="jumbotron jumbotron-sized jumboalign">
  <div class="bg">
  </div>
  <div class="content">
   <iframe width="854" height="480" src="https://www.youtube.com/embed/pn5bX7yGQDs" frameborder="0" allowfullscreen></iframe>
  </div>
</div>


<div class="jumbotron jumbotron-sized jumboalign">
  <div class="bg">
  </div>
  <div>Lyric video submitted by a fan for a song off Call of the Siren.</div>
  <div class="content">
    <iframe width="854" height="480" src="https://www.youtube.com/embed/2AV8_IgRGK4" frameborder="0" allowfullscreen></iframe>
  </div>
</div>

<div class="jumbotron jumbotron-sized jumboalign">
  <div class="bg">
  </div>
  <div>Official music video for Low Lies Lenore from the Offended Youth album.</div>
  <div class="content">
  <iframe width="854" height="480" src="https://www.youtube.com/embed/cifrbUkVrTk" frameborder="0" allowfullscreen></iframe>
  </div>
</div>

<div class="jumbotron jumbotron-sized jumboalign">
  <div class="bg">
  </div>
  <div>Live footage of Death is a Dialogue playing with Hawthorne Heights at Masquerade.</div>
  <div class="content">
    <iframe width="854" height="480" src="https://www.youtube.com/embed/KjCG0owbvFg" frameborder="0" allowfullscreen></iframe>
  </div>
</div>

<%= yield %>

</body>
<div id="footerlinks">
<footer class="modal-footer" >
  <div class="container">
   <span>Book a Show=></span><span class="textright container"><=Press Stuff</span><br>
<%= mail_to 'arlington6988@yahoo.com', 'US Booking', subject: "US:ENTERDATE" %><span class="textright container"><%= link_to "Download", diad_download_path %></span><br>
<%= mail_to 'arlington6988@yahoo.com', 'EU Booking', subject: "EU:ENTERDATE" %><span class="textright container"><%= link_to "About", diad_about_path %></span><br>

  </div>
  </div
</footer>
</html>

diad/app/views/diad/items.html.erb
<html>
<head>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.6.1/css/font-awesome.min.css">
  <title>DeathisaDialogue | Official Site</title>
  <%= stylesheet_link_tag    'application', 'diadmain', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <%= favicon_link_tag 'favicon.png' %>

  <nav class="navbar navbar-default navbar-fixed-top headblack" role="navigation">
    <div class="navbar-header">
      <a class="navbar-brand" href="http://www.deathisadialogue.com">
        <%= image_tag("Logoandname.png") %>
      </a>
    </div>
    <%= form_tag('http://www.fanbridge.com/signup/1.5/submit?userid=67920', id: 'fanbridgesignup', authenticity_token: false, method: :post, remote: true, class: "nav-inline form-inline") do %>
        <%= text_field_tag 'firstname', nil, placeholder: 'First Name', size: 8, class: 'form-controle-xsm form-email' %>
        <%= text_field_tag 'lastname', nil, placeholder: 'Last Name', size: 8, class: 'form-controle-xsm form-email' %>
        <%= text_field_tag 'email', nil, placeholder: 'Email', size: 20, class: 'form-control-xsm form-email' %>
        <%= text_field_tag 'zip', nil, placeholder: 'Zipcode', size: 6, class: 'form-control-xsm form-email' %>
        <%= submit_tag "Get Updates!", onclick: "alertify.success('Got it! We will be in touch.', function() {},'popup1');", class: 'btn btn-default btn-sm btn-email' %>
    <% end %>
    <% unless current_user.nil? %>
    <%= button_to "Logout", log_out_path, class: "btn btn-default btn-sm btn-email topcorner", method: :get %>
        <% end %>
    <script>
      $("#fanbridgesignup").bind("ajax:send", function(e){
        $("#firstname").val('');
        $("#lastname").val('');
        $("#email").val('');
        $("#zip").val('');
      });
    </script>
    <div id="genlinks">
      <div class="container">
        <ul class="nav nav-bar navbar-nav">
          <li ><%= link_to "News", root_path %>
            <%= link_to "Tour", root_path %>
            <%= link_to "Music", diad_music_path %>
            <%= link_to "Videos", root_path %>
            <%= link_to "Photos", diad_photos_path %>
            <%= link_to "Store", diad_products_path %>
            <span class="pull-lg-right fontset">
            <%= link_to 'Cart/Checkout', diad_store_viewcart_path, :class=> "fa fa-shopping-cart navbar-right fa-5x" %>
            </span>
            <%= text_field_tag 'Total', nil, :size => '6', value: @total, class: 'fieldfont pull-right pull-lg-right', disabled: 'true' %>
            <%= label_tag 'Total:', nil, class: 'fontset pull-right pull-lg-right' %>
            <div id="notice" class="pull-right fontset"><%= notice %></div>
          </li>
        </ul>
      </div>
    </div>
  </nav>
</head>
<body class="navbargrey topspace">
      <% @items.each.first(4).each do |i| %>
              <div class="container-fluid col-md-4">
                <div class="row text-sm-center fontset">

                  <h4><%= i.name %></h4>
<!--                  <img src="http://placehold.it/200x200" alt="..." class="img-responsive"/> -->
                  <%= image_tag i.photo, :class => "img-responsive" %>
                  <p><%= i.description %><br>
                  <%= i.displayprice %>
                  </p>
                <%= form_tag(diad_store_addtocart_path, method: "get", :class => 'fieldfont') do %>
                    <%= hidden_field(:quantity, params[:quantity] ) %>
                    <%= hidden_field(:itemid, params[:itemid], value: i.id) %>
		    <% unless i.size.nil? %>
                      <%= select_tag :size, options_for_select([ "S", "M", "L", "XL" ]) %>
                    <% end %>
                    <%= submit_tag("Add To Cart", id: "cartadd", :class => 'btn-store btn-sm fontset') %>
                <% end %>
                </div>
              </div>
      <% end %>
</body>
</html>

diad/app/views/diad/musicsimple.html.erb
<html>
<head>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.6.1/css/font-awesome.min.css">
  <title>DeathisaDialogue | Official Site</title>
  <%= stylesheet_link_tag    'application', 'diadmain', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <%= favicon_link_tag 'favicon.png' %>

  <nav class="navbar navbar-default navbar-fixed-top headblack" role="navigation">
    <div class="navbar-header">
      <a class="navbar-brand" href="http://www.deathisadialogue.com">
        <%= image_tag("Logoandname.png") %>
      </a>
    </div>
    <%= form_tag('http://www.fanbridge.com/signup/1.5/submit?userid=67920', id: 'fanbridgesignup', authenticity_token: false, method: :post, remote: true, class: "nav-inline form-inline") do %>
        <%= text_field_tag 'firstname', nil, placeholder: 'First Name', size: 8, class: 'form-controle-xsm form-email' %>
        <%= text_field_tag 'lastname', nil, placeholder: 'Last Name', size: 8, class: 'form-controle-xsm form-email' %>
        <%= text_field_tag 'email', nil, placeholder: 'Email', size: 20, class: 'form-control-xsm form-email' %>
        <%= text_field_tag 'zip', nil, placeholder: 'Zipcode', size: 6, class: 'form-control-xsm form-email' %>
        <%= submit_tag "Get Updates!", onclick: "alertify.success('Got it! We will be in touch.', function() {},'popup1');", class: 'btn btn-default btn-sm btn-email' %>
    <% end %>
    <script>
      $("#fanbridgesignup").bind("ajax:send", function(e){
        $("#firstname").val('');
        $("#lastname").val('');
        $("#email").val('');
        $("#zip").val('');
      });
    </script>
    <div id="genlinks">
      <div class="container">
        <ul class="nav nav-bar navbar-nav">
          <li ><%= link_to "News", root_path %>
            <%= link_to "Tour", root_path %>
            <%= link_to "Music", diad_music_path %>
            <%= link_to "Videos", root_path %>
            <%= link_to "Photos", diad_photos_path %>
            <%= link_to "Store", diad_products_path %>
            <%= link_to '', "https://www.facebook.com/deathisadialogue", :class => "fa fa-facebook navbar-right", :target => '_blank' %>
            <%= link_to '', "https://www.twitter.com/deathisadialog", :class=> "fa fa-twitter navbar-right", :target => '_blank' %>
            <%= link_to '', "https://play.spotify.com/album/5LfJ9J6lwySoakYxnlqXOH", :class=> "fa fa-spotify navbar-right", :target => '_blank' %>
            <%= link_to '', "https://www.instagram.com/jasonleediad", :class=> "fa fa-instagram navbar-right", :target => '_blank' %>
            <%= link_to '', "https://www.youtube.com/user/Deathisadialogue/videos", :class=> "fa fa-youtube navbar-right", :target => '_blank' %>
          </li>
        </ul>
      </div>
    </div>
  </nav>
</head>
</html>

<body class="backgroundmusic">
  <audio controls="controls", class="player">
   <source src="<%= audio_path 'Callofthesirensamples.mp3'%>" type="audio/mpeg" />
   <source src="<%= audio_path 'Callofthesirensamples.ogg'%>" type="audio/ogg" />
  </audio>
</body>
</html>

diad/app/views/diad/news.html.erb
<html>
<h1>This is where news goes</h1>
</html>

diad/app/views/diad/photos.html.erb
<head>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.6.1/css/font-awesome.min.css">
  <title>DeathisaDialogue | Official Site</title>
  <%= stylesheet_link_tag    'application', 'diadmain', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <%= favicon_link_tag 'favicon.png' %>

  <nav class="navbar navbar-default navbar-fixed-top headblack" role="navigation">
    <div class="navbar-header">
      <a class="navbar-brand" href="http://www.deathisadialogue.com">
        <%= image_tag("Logoandname.png") %>
      </a>
    </div>
    <%= form_tag('http://www.fanbridge.com/signup/1.5/submit?userid=67920', id: 'fanbridgesignup', authenticity_token: false, method: :post, remote: true, class: "nav-inline form-inline") do %>
        <%= text_field_tag 'firstname', nil, placeholder: 'First Name', size: 8, class: 'form-controle-xsm form-email' %>
        <%= text_field_tag 'lastname', nil, placeholder: 'Last Name', size: 8, class: 'form-controle-xsm form-email' %>
        <%= text_field_tag 'email', nil, placeholder: 'Email', size: 20, class: 'form-control-xsm form-email' %>
        <%= text_field_tag 'zip', nil, placeholder: 'Zipcode', size: 6, class: 'form-control-xsm form-email' %>
        <%= submit_tag "Get Updates!", onclick: "alertify.success('Got it! We will be in touch.', function() {},'popup1');", class: 'btn btn-default btn-sm btn-email' %>
    <% end %>
    <script>
      $("#fanbridgesignup").bind("ajax:send", function(e){
        $("#firstname").val('');
        $("#lastname").val('');
        $("#email").val('');
        $("#zip").val('');
      });
    </script>
    <div id="genlinks">
      <div class="container">
        <ul class="nav nav-bar navbar-nav">
          <li ><%= link_to "News", root_path %>
            <%= link_to "Tour", root_path %>
            <%= link_to "Music", diad_music_path %>
            <%= link_to "Videos", root_path %>
            <%= link_to "Photos", diad_photos_path %>
            <%= link_to "Store", diad_products_path %>
            <%= link_to '', "https://www.facebook.com/deathisadialogue", :class => "fa fa-facebook navbar-right", :target => '_blank' %>
            <%= link_to '', "https://www.twitter.com/deathisadialog", :class=> "fa fa-twitter navbar-right", :target => '_blank' %>
            <%= link_to '', "https://play.spotify.com/album/5LfJ9J6lwySoakYxnlqXOH", :class=> "fa fa-spotify navbar-right", :target => '_blank' %>
            <%= link_to '', "https://www.instagram.com/jasonleediad", :class=> "fa fa-instagram navbar-right", :target => '_blank' %>
            <%= link_to '', "https://www.youtube.com/user/Deathisadialogue/videos", :class=> "fa fa-youtube navbar-right", :target => '_blank' %>
          </li>
        </ul>
      </div>
    </div>
  </nav>
</head>

<body class="navbargrey">
<div  class="container topspacedeep">
 <%= image_tag('mainpoolshotWEB.jpg', :class => 'center-block') %><br>
  <%= image_tag('diadcreepy.jpg', :class => 'center-block') %><br>
  <%= image_tag('diadgrassmain.jpg', :class => 'center-block') %><br>

</div>
</body>

diad/app/views/diad/thankyou.html.erb
<head>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.6.1/css/font-awesome.min.css">
  <title>DeathisaDialogue | Official Site</title>
  <%= stylesheet_link_tag    'application', 'diadmain', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <%= favicon_link_tag 'favicon.png' %>

  <nav class="navbar navbar-default navbar-fixed-top headblack" role="navigation">
    <div class="navbar-header">
      <a class="navbar-brand" href="http://www.deathisadialogue.com">
        <%= image_tag("Logoandname.png") %>
      </a>
    </div>
    <%= form_tag('http://www.fanbridge.com/signup/1.5/submit?userid=67920', id: 'fanbridgesignup', authenticity_token: false, method: :post, remote: true, class: "nav-inline form-inline") do %>
        <%= text_field_tag 'firstname', nil, placeholder: 'First Name', size: 8, class: 'form-controle-xsm form-email' %>
        <%= text_field_tag 'lastname', nil, placeholder: 'Last Name', size: 8, class: 'form-controle-xsm form-email' %>
        <%= text_field_tag 'email', nil, placeholder: 'Email', size: 20, class: 'form-control-xsm form-email' %>
        <%= text_field_tag 'zip', nil, placeholder: 'Zipcode', size: 6, class: 'form-control-xsm form-email' %>
        <%= submit_tag "Get Updates!", onclick: "alertify.success('Got it! We will be in touch.', function() {},'popup1');", class: 'btn btn-default btn-sm btn-email' %>
    <% end %>
    <script>
      $("#fanbridgesignup").bind("ajax:send", function(e){
        $("#firstname").val('');
        $("#lastname").val('');
        $("#email").val('');
        $("#zip").val('');
      });
    </script>
    <div id="genlinks">
      <div class="container">
        <ul class="nav nav-bar navbar-nav">
          <li ><%= link_to "News", root_path %>
            <%= link_to "Tour", "#{root_path}#tour" %>
            <%= link_to "Music", diad_music_path %>
            <%= link_to "Videos", "#{root_path}#video" %>
            <%= link_to "Photos", diad_photos_path %>
            <%= link_to "Store", diad_products_path %>
            <%= link_to '', "https://www.facebook.com/deathisadialogue", :class => "fa fa-facebook navbar-right", :target => '_blank' %>
            <%= link_to '', "https://www.twitter.com/deathisadialog", :class=> "fa fa-twitter navbar-right", :target => '_blank' %>
            <%= link_to '', "https://play.spotify.com/album/5LfJ9J6lwySoakYxnlqXOH", :class=> "fa fa-spotify navbar-right", :target => '_blank' %>
            <%= link_to '', "https://www.instagram.com/jasonleediad", :class=> "fa fa-instagram navbar-right", :target => '_blank' %>
            <%= link_to '', "https://www.youtube.com/user/Deathisadialogue/videos", :class=> "fa fa-youtube navbar-right", :target => '_blank' %>
          </li>
        </ul>
      </div>
    </div>
  </nav>
</head>
<script>
  alertify.success('Thanks for your purchase! A receipt was emailed to the email address associated with your account.', function() {},'popup1');
</script>
<body class="navbargrey">
<div  class="container topspacedeep">
  <div id="notice" class="fontset text-danger text-sm-center"><%= notice %></div>
  <%= image_tag('diadcreepy.jpg', :class => 'center-block') %><br>

</div>
</body>

diad/app/views/diad/tour.html.erb
<html>
<h1>This is where Tour goes</h1>
</html>

diad/app/views/diad/videos.html.erb
<html>
<h1>This is where videos goes</h1>
</html>